// Import dynamically loaded photos from generated manifest
// The manifest is auto-generated by scripts/generate-photo-manifest.js
// Run: node scripts/generate-photo-manifest.js to regenerate after adding photos
import { CAMERA_ROLL_PHOTOS, PHOTO_LIBRARY_PHOTOS } from './photoManifest';

const WALLPAPERS = Array.from({ length: 12 }, (_, i) => `/assets/wallpapers/Wallpaper${i + 1}.webp`);

export function AboutPage() {
  return (
    <div className="iphone-photos-page">
      {/* Blank for now */}
    </div>
  );
}

export function ContactPage() {
  return (
    <div className="iphone-photos-page">
      {/* Blank for now */}
    </div>
  );
}

interface WallpaperPageProps {
  onPhotoSelect?: (index: number) => void;
}

export function WallpaperPage({ onPhotoSelect }: WallpaperPageProps) {
  return (
    <div className="iphone-photos-page">
      <div className="iphone-wallpaper-grid">
        {CAMERA_ROLL_PHOTOS.map((photo, index) => (
          <button
            key={index}
            className="iphone-wallpaper-thumbnail"
            onClick={() => onPhotoSelect?.(index)}
          >
            <img src={photo} alt={`Photo ${index + 1}`} />
          </button>
        ))}
      </div>
    </div>
  );
}

interface PhotoLibraryPageProps {
  onPhotoSelect?: (index: number) => void;
}

export function PhotoLibraryPage({ onPhotoSelect }: PhotoLibraryPageProps) {
  return (
    <div className="iphone-photos-page">
      <div className="iphone-wallpaper-grid">
        {PHOTO_LIBRARY_PHOTOS.map((photo, index) => (
          <button
            key={index}
            className="iphone-wallpaper-thumbnail"
            onClick={() => onPhotoSelect?.(index)}
          >
            <img src={photo} alt={`Photo ${index + 1}`} />
          </button>
        ))}
      </div>
    </div>
  );
}

export { CAMERA_ROLL_PHOTOS, PHOTO_LIBRARY_PHOTOS };

